esphome:
  name: esphome-web-9dd449
  friendly_name: ESPHome GPS
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  
# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

web_server:
  version: 3
  local: true

external_components:
  - source: github://andrewbackway/esphome-gps_idf

uart:
  - id: uart_gps
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 9600

gps_idf:
  id: gps
  uart_id: uart_gps

sensor:
  - platform: gps_idf
    gps_idf_id: gps
    type: latitude
    name: "GPS Latitude"
  - platform: gps_idf
    gps_idf_id: gps
    type: longitude
    name: "GPS Longitude"
  - platform: gps_idf
    gps_idf_id: gps
    type: altitude
    name: "GPS Altitude"
  - platform: gps_idf
    gps_idf_id: gps
    type: speed
    name: "GPS Speed"
  - platform: gps_idf
    gps_idf_id: gps
    type: course
    name: "GPS Course"
  - platform: gps_idf
    gps_idf_id: gps
    type: satellites
    name: "GPS Satellites"
  - platform: gps_idf
    gps_idf_id: gps
    type: hdop
    name: "GPS HDOP"

text_sensor:
  - platform: gps_idf
    gps_idf_id: gps
    type: datetime
    name: "GPS DateTime"
  - platform: gps_idf
    gps_idf_id: gps
    type: fix_status
    name: "GPS Fix Status"
